name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "Docker Hub Username: ${{ secrets.DOCKER_HUB_TOKEN }}"
        echo "Docker Hub Access Token: ${{ secrets.DOCKER_HUB_USERNAME }}"
        echo "${{ secrets.DOCKER_HUB_USERNAME }}" | docker login \
            -u "${{ secrets.DOCKER_HUB_TOKEN }}" --password-stdin docker.io
        docker build . --file mlops74/dockerfiles/train_model.dockerfile \
            --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker build . --file mlops74/dockerfiles/train_model2.dockerfile \
            --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
        docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
